#!/usr/bin/bash
#
# Created by Peter Lawrence - lawrence@ucar.edu
# National Center for Atmospheric Research
# CESM Time Series Generation Tools 1.0
# Copy All the Restart Directories from the Archive to the Timeseries Directory for an Experiment Group and Experiment Pair
#

if [ ${#} -ne 2 ]
then
    echo "Usage: runcopyrestartsallexperimentgrouptimeseriesfiles experimentgroup experiment"
    exit
fi

if [ -f ./toolsconfig ]; 
then
    source ./toolsconfig
fi

if [ -f ../toolsconfig ]; 
then
    source ../toolsconfig
fi

experimentgroup=${1}
experiment=${2}

python ${scriptsdir}copyrestartsallexperimentgrouptimeseriesfiles.py ${experimentgroup} ${experimentgrouphistorylist} ${experiment} ${experimentlist}






