#!/usr/bin/bash
#
# Created by Peter Lawrence - lawrence@ucar.edu
# National Center for Atmospheric Research
# CESM Time Series Generation Tools 1.0
# Generates Time Series Status Report for an Experiment Group, History File Type and Experiment Name
#

if [ ${#} -ne 3 ]
then
    echo "Usage: runstatusexperimentgrouptimeseriesfiles experimentgroup historyfiletype experiment"
    exit
fi

if [ -f ./toolsconfig ]; 
then
    source ./toolsconfig
fi

if [ -f ../toolsconfig ]; 
then
    source ../toolsconfig
fi

experimentgroup=${1}
historyfiletype=${2}
experiment=${3}

python ${scriptsdir}statusexperimentgrouptimeseriesfiles.py ${experimentgroup} ${historyfiletype} ${experimentgrouphistorylist} ${experiment} ${experimentlist} ${variablefilesdir}






