#!/usr/bin/bash
#
# Created by Peter Lawrence - lawrence@ucar.edu
# National Center for Atmospheric Research
# CESM Time Series Generation Tools 1.0
# Submits All the Generate Time Series Variable Files for an Experiment Group and Experiment Name 
# Over a Time Period that corresponds to 10 Year and Final Time Blocks for the Experiment
#

if [ ${#} -ne 4 ]
then
    echo "Usage: runsubmitgenerateallexperimentgrouptimeseriesfiles experimentgroup experiment startyear endyear"
    exit
fi

if [ -f ./toolsconfig ]; 
then
    source ./toolsconfig
fi

if [ -f ../toolsconfig ]; 
then
    source ../toolsconfig
fi

experimentgroup=${1}
experiment=${2}
startyear=${3}
endyear=${4}

submitgenerateexperimentgroupcommand="${toolsdir}runsubmitgeneratevariablelistexperimentgrouptimeseriesfiles"

python ${scriptsdir}submitgenerateallexperimentgrouptimeseriesfiles.py ${experimentgroup} ${experimentgrouphistorylist} ${experiment} ${experimentlist} ${startyear} ${endyear} ${submitgenerateexperimentgroupcommand}






