#!/usr/bin/bash
#
# Created by Peter Lawrence - lawrence@ucar.edu
# National Center for Atmospheric Research
# CESM Time Series Generation Tools 1.0
# Submits the Generate Time Series Variable Files for an Experiment Group, History File Type, Variable Name and Experiment Name 
# Over a Time Period that corresponds to 10 Year and Final Time Blocks for the Experiment
#

if [ ${#} -ne 6 ]
then
    echo "Usage: runsubmitgenerateexperimentgrouptimeseriesfiles experimentgroup historyfiletype variablename experiment startyear endyear"
    exit
fi

if [ -f ./toolsconfig ]; 
then
    source ./toolsconfig
fi

if [ -f ../toolsconfig ]; 
then
    source ../toolsconfig
fi

experimentgroup=${1}
historyfiletype=${2}
variablename=${3}
experiment=${4}
startyear=${5}
endyear=${6}

generateexperimentgroupcommand="${toolsdir}rungenerateexperimentgrouptimeseriesfiles"
updateexperimentgroupcommand="${toolsdir}runupdateexperimentgrouptimeseriesfiles"

python ${scriptsdir}submitgenerateexperimentgrouptimeseriesfiles.py ${experimentgroup} ${historyfiletype} ${experimentgrouphistorylist} ${experiment} ${experimentlist} ${variablename} ${variablefilesdir} ${startyear} ${endyear} ${generateexperimentgroupcommand} ${updateexperimentgroupcommand} ${queuename} ${projectcode}






