#!/usr/bin/bash
#
# Created by Peter Lawrence - lawrence@ucar.edu
# National Center for Atmospheric Research
# CESM Time Series Generation Tools 1.0
# Submits the Generate Time Series Variable Files for an Experiment Group, History File Type and Experiment Name 
# Over a Time Period that corresponds to 10 Year and Final Time Blocks for the Experiment
#


if [ ${#} -ne 5 ]
then
    echo "Usage: runsubmitgeneratevariablelistexperimentgrouptimeseriesfiles experimentgroup historyfiletype experiment startyear endyear"
    exit
fi

if [ -f ./toolsconfig ]; 
then
    source ./toolsconfig
fi

if [ -f ../toolsconfig ]; 
then
    source ../toolsconfig
fi

experimentgroup=${1}
historyfiletype=${2}
experiment=${3}
startyear=${4}
endyear=${5}

generateexperimentgroupcommand="${toolsdir}rungenerateexperimentgrouptimeseriesfiles"
updateexperimentgroupcommand="${toolsdir}runupdateexperimentgrouptimeseriesfiles"

python ${scriptsdir}submitgeneratevariablelistexperimentgrouptimeseriesfiles.py ${experimentgroup} ${historyfiletype} ${experimentgrouphistorylist} ${experiment} ${experimentlist} ${variablefilesdir} ${startyear} ${endyear} ${generateexperimentgroupcommand} ${updateexperimentgroupcommand} ${queuename} ${projectcode}






